settings:
  legacy:
    force: false
    interval: 0s
schema:
- name: mrbotchi
  path: .
  commands:
    install:
      status: true
      method: go build -o ./bin/mrbotchi
    run:
      status: true
      method: ./bin/mrbotchi
    watcher:
    extensions:
    - go
    paths:
    - /
    ignored_paths:
    - .git
    - .realize
    - vendor
