version: '3.7'

services:
  postgres:
    image: postgres:12-alpine
    restart: always
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks: 
      - internal_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mrbotchi

  migrate:
    image: migrate/migrate
    volumes:
      - ./migrate:/migrations
    networks: 
      - internal_network

  mrbotchi:
    build:
      context: .
      target: dev
    restart: always
    links:
      - postgres
    volumes:
      - ./:/go/src/github.com/mrbotchi-team/mrbotchi
      - ./.config:/.config
    ports:
      - 3000:3000
    networks: 
      - internal_network
      - external_network

  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - 80:80
      - 443:443
    networks: 
      - internal_network
      - external_network
    environment:
      DOMAINS: 'mrbotchi.test -> http://mrbotchi:3000'
      STAGE: 'local'

networks: 
  internal_network:
    internal: true
  external_network:
