version: '3.7'

x-template: &flyway-template
  image: boxfuse/flyway:latest
  volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/conf:/flyway/conf
  depends_on:
    - postgres

services:
  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    networks: 
      - internal_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mr_botchi
  
  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - 80:80
      - 443:443
    networks: 
      - internal_network
      - external_network
    environment:
      DOMAINS: 'mrbotchi.test -> http://backend:3000'
      STAGE: 'local'

  backend:
    build: 
      context: .
      target: dev
    restart: always
    links:
      - postgres
    volumes:
      - ./:/go/src/github.com/mr-botchi/backend
    command: realize start --run
    ports:
      - 3000:3000
    networks: 
      - internal_network

networks: 
  internal_network:
    internal: true
  external_network: