version: '3.7'

x-template: &flyway-template
  image: boxfuse/flyway:latest-alpine
  volumes:
    - ./flyway/sql:/flyway/sql
    - ./flyway/conf:/flyway/conf
  depends_on:
    - postgres

services:
  flyway-clean:
    <<: *flyway-template
    command: clean

  flyway-migrate:
    <<: *flyway-template
    command: migrate

  flyway-info:
    <<: *flyway-template
    command: info

  postgres:
    image: postgres:12-alpine
    restart: always
    ports:
      - 5432:5432
    networks: 
      - internal_network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: mrbotchi

  mrbotchi:
    build: 
      context: .
      target: prod
    restart: always
    links:
      - postgres
    volumes:
      - ./:/go/src/github.com/mrbotchi-team/mrbotchi
      - ./.config:/.config
    #command: realize start --run
    ports:
      - 3000:3000
    networks: 
      - internal_network

  https-portal:
    image: steveltn/https-portal:1
    restart: always
    ports:
      - 80:80
      - 443:443
    networks: 
      - internal_network
      - external_network
    environment:
      DOMAINS: 'mrbotchi.test -> http://mrbotchi:3000'
      STAGE: 'local'

networks: 
  internal_network:
    internal: true
  external_network:
