host = "mrbotchi.test"
port = 3000
paseto_key = "3mIzbGcvJxZoAi2vpM65HvA6R61VyEht"

[database]
host = "postgres"
port = 5432
user = "user"
password = "qwerty"
dbname = "mrbotchi"

[argon2]
memory_cost = 64
iteration_cost = 4
parallelism = 2
salt_length = 16
key_length = 32

# このオプションは廃止される予定です。
# This option will be deprecated.
[user]
name = "mrbotchi"
display_name = "MrBotchiのおっさん"
public_key = "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHboHh+Jq/uYGffOwrpm1Zl1Zdnd6pJ8BHWR2AFS0xOB"
private_key = "-----BEGIN OPENSSH PRIVATE KEY-----b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZWQyNTUxOQAAACB26B4fiav7mBn3zsK6ZtWZdWXZ3eqSfAR1kdgBUtMTgQAAAJgjNh2rIzYqwAAAAtzc2gtZWQyNTUxOQAAACB26B4fiav7mBn3zsK6ZtWZdWXZ3eqSfAR1kdgBUtMTgQAAAEDG7GrwsXXVcztwuslJ1Ymkz5FEJLJSMykUrss3skga6XboHh+Jq/uYGffOwrpm1Zl1Zdnd6pJ8BHWR2AFS0xOBAAAAEGt1Z29AQ0xJLUxJTi0wMDEBAgMEBQ==-----END OPENSSH PRIVATE KEY-----"
